In [1]:
import pandas as pd
import os

# 1. Define exact paths provided by the user
base_dir = "../data/Retail"
demand_file = os.path.join(base_dir, "Retail_Demand_Outlook_4170_E_Ponce_de_Leon_Ave_Clarkston_Georgia_30021_2.xlsx")
budget_file = os.path.join(base_dir, "Household_Budget_Expenditures_4170_E_Ponce_de_Leon_Ave_Clarkston_Georgia_30021_2_2.xlsx")

# 2. Load the data using openpyxl
print("Loading data...")
df_demand = pd.read_excel(demand_file, header=None, engine='openpyxl')
df_budget = pd.read_excel(budget_file, header=None, engine='openpyxl')

def extract_numbers_from_row(df, search_term):
    """
    Finds the row containing the search term, strips text/commas, 
    and returns a clean dictionary of the Current and Future values across the 3 rings.
    """
    # Find the row that contains the exact search term (case-insensitive)
    mask = df.apply(lambda row: row.astype(str).str.contains(search_term, case=False, regex=False).any(), axis=1)
    if not mask.any():
        print(f"Warning: '{search_term}' not found in the data.")
        return None
    
    row_data = df[mask].iloc[0]
    
    # Clean the row: remove commas and convert to pure numbers
    cleaned_row = row_data.astype(str).str.replace(',', '', regex=False).str.strip()
    numeric_values = pd.to_numeric(cleaned_row, errors='coerce').dropna().tolist()
    
    # Filter out percentages (like Tapestry Segments which are < 1.0)
    numeric_values = [n for n in numeric_values if n > 1.0]
    
    # Esri horizontally outputs: 0-2m(Current, Future), 2-3m(Current, Future), 3-5m(Current, Future)
    if len(numeric_values) >= 6:
        return {
            '0-2_Mile_Current': numeric_values[0],
            '0-2_Mile_Future': numeric_values[1],
            '2-3_Mile_Current': numeric_values[2],
            '2-3_Mile_Future': numeric_values[3],
            '3-5_Mile_Current': numeric_values[4],
            '3-5_Mile_Future': numeric_values[5],
        }
    return None

# ==========================================
# STEP 1: EXTRACT DEMOGRAPHICS
# ==========================================
# We use the Budget file because the demographics rows are cleaner
demographics = {}
for demo in ['Population', 'Households', 'Median Household Income']:
    data = extract_numbers_from_row(df_budget, demo)
    if data:
        demographics[demo] = data

df_demo = pd.DataFrame(demographics).T

# ==========================================
# STEP 2: EXTRACT RETAIL EXPENDITURES
# ==========================================
# Map the sub-categories into your main buckets
categories = {
    'NG&S': ['Food at Home', 'Personal Care Products', 'Housekeeping Supplies'],
    'F&B': ['Food Away from Home', 'Alcoholic Beverages'],
    'GAFO': ['Apparel and Services', 'Entertainment & Recreation', 'Household Furnishings and Equipment']
}

exp_results = []
for bucket, sub_cats in categories.items():
    for cat in sub_cats:
        data = extract_numbers_from_row(df_demand, cat)
        if data:
            exp_results.append({
                'Bucket': bucket,
                'Category': cat,
                '0-2_Mile_Current': data['0-2_Mile_Current'],
                '2-3_Mile_Current': data['2-3_Mile_Current'],
                '3-5_Mile_Current': data['3-5_Mile_Current'],
                '0-2_Mile_Future': data['0-2_Mile_Future'],
                '2-3_Mile_Future': data['2-3_Mile_Future'],
                '3-5_Mile_Future': data['3-5_Mile_Future'],
            })

df_expenditures = pd.DataFrame(exp_results)

# ==========================================
# STEP 3: CALCULATE SUPPORTABLE SF (GAP ANALYSIS)
# ==========================================
# Note: Since the Esri reports provided do not contain existing store sales (Supply), 
# we calculate the Gap by determining what percentage of local demand your project can capture.

benchmarks = {'NG&S': 550, 'F&B': 650, 'GAFO': 400} # Industry average sales needed per SF
capture_rate = 0.15 # Assuming your project captures 15% of the local 0-2 mile market

df_analysis = df_expenditures.copy()
# Calculate how many dollars you capture
df_analysis['Target Capture ($) (0-2m)'] = df_analysis['0-2_Mile_Current'] * capture_rate
df_analysis['Sales per SF Benchmark'] = df_analysis['Bucket'].map(benchmarks)

# Calculate the square footage supported by those dollars
df_analysis['Supportable SF (0-2m)'] = (df_analysis['Target Capture ($) (0-2m)'] / df_analysis['Sales per SF Benchmark']).round(0)

# ==========================================
# OUTPUT TO CONSOLE (with comma formatting for numbers)
# ==========================================
pd.set_option('display.float_format', '{:,.0f}'.format) # Format for comma as thousand separator

def format_columns_with_commas(df, cols):
    df_fmt = df.copy()
    for col in cols:
        if col in df_fmt.columns:
            df_fmt[col] = df_fmt[col].apply(lambda x: '{:,.0f}'.format(x) if pd.notnull(x) else x)
    return df_fmt

print("\n--- DEMOGRAPHIC BASE (CURRENT YEAR) ---")
demo_cols = ['0-2_Mile_Current', '2-3_Mile_Current', '3-5_Mile_Current']
print(format_columns_with_commas(df_demo, demo_cols)[demo_cols])

print("\n--- CATEGORY EXPENDITURE (CURRENT YEAR) ---")
cat_cols = ['0-2_Mile_Current', '2-3_Mile_Current', '3-5_Mile_Current']
print(format_columns_with_commas(df_expenditures, ['0-2_Mile_Current', '2-3_Mile_Current', '3-5_Mile_Current'])[['Bucket', 'Category', '0-2_Mile_Current', '2-3_Mile_Current', '3-5_Mile_Current']])

print("\n--- SUPPORTABLE SQUARE FOOTAGE CALCULATION (0-2 MILE RING | 15% CAPTURE) ---")
analysis_cols = ['0-2_Mile_Current', 'Target Capture ($) (0-2m)', 'Supportable SF (0-2m)']
print(format_columns_with_commas(df_analysis, analysis_cols)[['Bucket', 'Category'] + analysis_cols])

# Optional: Save to a new clean CSV for your proforma
# df_analysis.to_csv(os.path.join(base_dir, "Cleaned_Retail_Demand_Analysis.csv"), index=False)

Loading data...

/Users/elyas/Applications/anaconda3/lib/python3.11/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

--- DEMOGRAPHIC BASE (CURRENT YEAR) ---
                        0-2_Mile_Current 2-3_Mile_Current 3-5_Mile_Current
Population                        59,183           55,073          165,981
Households                        21,387           22,539           67,761
Median Household Income           68,567           74,545           89,712

--- CATEGORY EXPENDITURE (CURRENT YEAR) ---
  Bucket                    Category 0-2_Mile_Current 2-3_Mile_Current  \
0   NG&S                Food at Home      139,369,490       18,213,601
1   NG&S      Personal Care Products       11,724,578        1,538,639
2   NG&S       Housekeeping Supplies       16,023,778        2,094,376
3    F&B         Food Away from Home       78,189,105       10,219,449
4    F&B         Alcoholic Beverages       12,042,192        1,569,034
5   GAFO        Apparel and Services       46,968,852        6,142,133
6   GAFO  Entertainment & Recreation       71,766,922        9,351,036

  3-5_Mile_Current
0      190,703,098
1       15,947,467
2       21,983,362
3      106,323,914
4       17,013,868
5       64,283,981
6      100,145,018

--- SUPPORTABLE SQUARE FOOTAGE CALCULATION (0-2 MILE RING | 15% CAPTURE) ---
  Bucket                    Category 0-2_Mile_Current  \
0   NG&S                Food at Home      139,369,490
1   NG&S      Personal Care Products       11,724,578
2   NG&S       Housekeeping Supplies       16,023,778
3    F&B         Food Away from Home       78,189,105
4    F&B         Alcoholic Beverages       12,042,192
5   GAFO        Apparel and Services       46,968,852
6   GAFO  Entertainment & Recreation       71,766,922

  Target Capture ($) (0-2m) Supportable SF (0-2m)
0                20,905,424                38,010
1                 1,758,687                 3,198
2                 2,403,567                 4,370
3                11,728,366                18,044
4                 1,806,329                 2,779
5                 7,045,328                17,613
6                10,765,038                26,913

In [2]:
df_expenditures.head(20)

,Bucket,Category,0-2_Mile_Current,2-3_Mile_Current,3-5_Mile_Current,0-2_Mile_Future,2-3_Mile_Future,3-5_Mile_Future
0,NG&S,Food at Home,"139,369,490","18,213,601","190,703,098","157,583,091","163,892,911","26,810,187"
1,NG&S,Personal Care Products,"11,724,578","1,538,639","15,947,467","13,263,217","13,679,762","2,267,705"
2,NG&S,Housekeeping Supplies,"16,023,778","2,094,376","21,983,362","18,118,154","18,896,574","3,086,788"
3,F&B,Food Away from Home,"78,189,105","10,219,449","106,323,914","88,408,554","91,338,829","14,985,085"
4,F&B,Alcoholic Beverages,"12,042,192","1,569,034","17,013,868","13,611,226","14,642,861","2,371,007"
5,GAFO,Apparel and Services,"46,968,852","6,142,133","64,283,981","53,110,985","55,237,789","9,046,192"
6,GAFO,Entertainment & Recreation,"71,766,922","9,351,036","100,145,018","81,117,958","86,193,633","13,951,385"

In [3]:
import pandas as pd
import os

# 1. Define paths
base_dir = "../data/Retail"
demand_file = os.path.join(base_dir, "Retail_Demand_Outlook_4170_E_Ponce_de_Leon_Ave_Clarkston_Georgia_30021_2.xlsx")
budget_file = os.path.join(base_dir, "Household_Budget_Expenditures_4170_E_Ponce_de_Leon_Ave_Clarkston_Georgia_30021_2_2.xlsx")

# 2. Load data
df_demand = pd.read_excel(demand_file, header=None, engine='openpyxl')
df_budget = pd.read_excel(budget_file, header=None, engine='openpyxl')

def extract_esri_values(df, search_term, is_expenditure=True):
    """
    Precisely extracts Current and Future values.
    Expenditures: 3-column blocks (Current, Future, Growth)
    Demographics: 2-column blocks (Current, Future)
    """
    mask = df.apply(lambda row: row.astype(str).str.contains(search_term, case=False, regex=False).any(), axis=1)
    if not mask.any():
        return None
    
    row_data = df[mask].iloc[0]
    cleaned_row = row_data.astype(str).str.replace(',', '', regex=False).str.strip()
    nums = pd.to_numeric(cleaned_row, errors='coerce').dropna().tolist()
    
    # Filter out small percentages/indices (usually < 1.0 or very small)
    nums = [n for n in nums if n > 1.0]

    if is_expenditure:
        # Expenditure blocks: [R1_Curr, R1_Fut, R1_Grw, R2_Curr, R2_Fut, R2_Grw, R3_Curr, R3_Fut, R3_Grw]
        # We target indices: 0, 1, 3, 4, 6, 7
        if len(nums) >= 8:
            return {
                'Curr_0_2': nums[0], 'Fut_0_2': nums[1],
                'Curr_2_3': nums[3], 'Fut_2_3': nums[4],
                'Curr_3_5': nums[6], 'Fut_3_5': nums[7]
            }
    else:
        # Demographic blocks: [R1_Curr, R1_Fut, R2_Curr, R2_Fut, R3_Curr, R3_Fut]
        # We target indices: 0, 1, 2, 3, 4, 5
        if len(nums) >= 6:
            return {
                'Curr_0_2': nums[0], 'Fut_0_2': nums[1],
                'Curr_2_3': nums[2], 'Fut_2_3': nums[3],
                'Curr_3_5': nums[4], 'Fut_3_5': nums[5]
            }
    return None

# ==========================================
# STEP 1: DEMOGRAPHICS (2-column mapping)
# ==========================================
demo_results = {}
for item in ['Population', 'Households', 'Median Household Income']:
    data = extract_esri_values(df_budget, item, is_expenditure=False)
    if data: demo_results[item] = data

df_demo = pd.DataFrame(demo_results).T

# ==========================================
# STEP 2: EXPENDITURES (3-column mapping)
# ==========================================
categories = {
    'NG&S': ['Food at Home', 'Personal Care Products', 'Housekeeping Supplies'],
    'F&B': ['Food Away from Home', 'Alcoholic Beverages'],
    'GAFO': ['Apparel and Services', 'Entertainment & Recreation']
}

exp_list = []
for bucket, sub_cats in categories.items():
    for cat in sub_cats:
        data = extract_esri_values(df_demand, cat, is_expenditure=True)
        if data:
            data.update({'Bucket': bucket, 'Category': cat})
            exp_list.append(data)

df_exp = pd.DataFrame(exp_list)

# ==========================================
# OUTPUT VALIDATION
# ==========================================
pd.set_option('display.float_format', '{:,.0f}'.format)
print("--- VERIFIED HOUSEHOLD COUNTS ---")
print(df_demo.loc[['Households']])

print("\n--- VERIFIED EXPENDITURES (2-3 MILE CORRECTED) ---")
# This should now show your manual calculation result (~163M) in the Current 2-3 Mile column
cols = ['Bucket', 'Category', 'Curr_0_2', 'Curr_2_3', 'Curr_3_5', 'Fut_0_2', 'Fut_2_3', 'Fut_3_5']
print(df_exp[cols])

/Users/elyas/Applications/anaconda3/lib/python3.11/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

--- VERIFIED HOUSEHOLD COUNTS ---
            Curr_0_2  Fut_0_2  Curr_2_3  Fut_2_3  Curr_3_5  Fut_3_5
Households    21,387   21,246    22,539   23,347    67,761   68,446

--- VERIFIED EXPENDITURES (2-3 MILE CORRECTED) ---
  Bucket                    Category    Curr_0_2    Curr_2_3    Curr_3_5  \
0   NG&S                Food at Home 139,369,490 163,892,911 586,849,015
1   NG&S      Personal Care Products  11,724,578  13,679,762  48,093,942
2   NG&S       Housekeeping Supplies  16,023,778  18,896,574  67,708,258
3    F&B         Food Away from Home  78,189,105  91,338,829 328,623,590
4    F&B         Alcoholic Beverages  12,042,192  14,642,861  54,066,844
5   GAFO        Apparel and Services  46,968,852  55,237,789 197,380,480
6   GAFO  Entertainment & Recreation  71,766,922  86,193,633 317,143,341

      Fut_0_2     Fut_2_3     Fut_3_5
0 157,583,091 190,703,098 667,403,080
1  13,263,217  15,947,467  54,688,588
2  18,118,154  21,983,362  76,978,477
3  88,408,554 106,323,914 373,841,225
4  13,611,226  17,013,868  61,527,422
5  53,110,985  64,283,981 224,518,227
6  81,117,958 100,145,018 360,712,478

In [4]:
df_exp.head()

,Curr_0_2,Fut_0_2,Curr_2_3,Fut_2_3,Curr_3_5,Fut_3_5,Bucket,Category
0,"139,369,490","157,583,091","163,892,911","190,703,098","586,849,015","667,403,080",NG&S,Food at Home
1,"11,724,578","13,263,217","13,679,762","15,947,467","48,093,942","54,688,588",NG&S,Personal Care Products
2,"16,023,778","18,118,154","18,896,574","21,983,362","67,708,258","76,978,477",NG&S,Housekeeping Supplies
3,"78,189,105","88,408,554","91,338,829","106,323,914","328,623,590","373,841,225",F&B,Food Away from Home
4,"12,042,192","13,611,226","14,642,861","17,013,868","54,066,844","61,527,422",F&B,Alcoholic Beverages

In [5]:
import pandas as pd
import os

# 1. Define exact paths
base_dir = "../data/Retail"
demand_file = os.path.join(base_dir, "Retail_Demand_Outlook_4170_E_Ponce_de_Leon_Ave_Clarkston_Georgia_30021_2.xlsx")

# 2. Define the Mapping Logic for Buckets
bucket_mapping = {
    'NG&S': ['Food at Home', 'Bakery', 'Meats', 'Dairy', 'Fruits', 'Snacks', 'Personal Care', 'Housekeeping', 'Smoking', 'Drugs'],
    'F&B': ['Food Away from Home', 'Alcoholic Beverages', 'Restaurants'],
    'GAFO': ['Apparel', 'Men\'s', 'Women\'s', 'Children\'s', 'Footwear', 'Watches', 'Jewelry', 'Computer', 'Software', 'Entertainment', 'Fees and Admissions', 'TV', 'Video', 'Audio', 'Pets', 'Toys', 'Sports', 'Furniture', 'Furnishings', 'Textiles', 'Appliances', 'Housewares', 'Luggage']
}

def assign_bucket(cat_name):
    """Maps granular categories to their respective industry buckets."""
    cat_lower = cat_name.lower()
    for bucket, keywords in bucket_mapping.items():
        for kw in keywords:
            if kw.lower() in cat_lower:
                return bucket
    return 'Other'

# 3. Load and Process Data
print("Loading Demand Data...")
df_demand = pd.read_excel(demand_file, header=None, engine='openpyxl')

granular_results = []

# Iterate through the rows (skipping report headers)
for i in range(19, len(df_demand)):
    cat_name = str(df_demand.iloc[i, 0]).strip()
    
    # Filter out empty rows, headers, and footer sources
    if cat_name in ['nan', ''] or 'mile' in cat_name.lower() or 'Source:' in cat_name:
        continue
    
    # Extract numeric values and strip commas
    row_vals = pd.to_numeric(df_demand.iloc[i, 1:].astype(str).str.replace(',', '', regex=False), errors='coerce').dropna().tolist()
    
    # Corrected Indexing logic (Skipping the Growth columns)
    # Index 0: R1_Curr | Index 1: R1_Fut | Index 3: R2_Curr | Index 4: R2_Fut | Index 6: R3_Curr | Index 7: R3_Fut
    if len(row_vals) >= 8:
        granular_results.append({
            'Bucket': assign_bucket(cat_name),
            'Category': cat_name,
            '0-2m_Current_2025': row_vals[0],
            '0-2m_Future_2030': row_vals[1],
            '2-3m_Current_2025': row_vals[3], # Verification: Should be ~163.8M for Food at Home
            '2-3m_Future_2030': row_vals[4],
            '3-5m_Current_2025': row_vals[6],
            '3-5m_Future_2030': row_vals[7]
        })

df_final = pd.DataFrame(granular_results)

# 4. Display & Export
pd.set_option('display.float_format', '{:,.0f}'.format)
print("\n--- GRANULAR RETAIL DATA WITH BUCKET MAPPING ---")
print(df_final.head(15))

# Export to a clean CSV for your Proforma
df_final.to_csv(os.path.join(base_dir, "Granular_Retail_Demand_Analysis.csv"), index=False)

Loading Demand Data...

--- GRANULAR RETAIL DATA WITH BUCKET MAPPING ---
   Bucket                                       Category  0-2m_Current_2025  \
0    GAFO                           Apparel and Services         46,968,852
1    GAFO                                          Men's          9,227,748
2    GAFO                                        Women's         15,620,036
3    GAFO                                     Children's          6,836,102
4    GAFO                                       Footwear         10,791,770
5    GAFO                              Watches & Jewelry          3,632,395
6    GAFO              Apparel Products and Services (1)            860,800
7    GAFO            Computers and Hardware for Home Use          4,381,080
8   Other                                Portable Memory             74,237
9    GAFO                              Computer Software            342,604
10   GAFO                           Computer Accessories            371,775
11  Other  Educational Books/Supplies/Other Expenditures          1,868,193
12  Other                          Other School Supplies          1,619,410
13   GAFO                     Entertainment & Recreation         71,766,922
14   GAFO                            Fees and Admissions         16,225,994

    0-2m_Future_2030  2-3m_Current_2025  2-3m_Future_2030  3-5m_Current_2025  \
0         53,110,985         55,237,789        64,283,981        197,380,480
1         10,434,001         10,859,665        12,639,777         38,956,403
2         17,663,057         19,002,977        22,098,818         68,040,660
3          7,730,068          7,571,395         8,811,384         26,599,408
4         12,204,167         12,261,767        14,292,310         43,481,923
5          4,106,686          4,521,755         5,254,969         16,563,669
6            973,006          1,020,230         1,186,723          3,738,417
7          4,954,698          5,197,343         6,052,767         18,525,189
8             84,023             90,168           105,216            313,953
9            387,772            409,561           478,629          1,412,563
10           420,402            441,495           514,597          1,588,104
11         2,113,744          2,198,872         2,565,193          7,758,436
12         1,831,078          1,934,637         2,249,942          6,969,609
13        81,117,958         86,193,633       100,145,018        317,143,341
14        18,334,968         19,588,483        22,722,561         73,576,337

    3-5m_Future_2030
0        224,518,227
1         44,309,429
2         77,391,529
3         30,241,013
4         49,465,745
5         18,857,199
6          4,253,312
7         21,075,426
8            357,350
9          1,608,321
10         1,808,170
11         8,821,751
12         7,925,570
13       360,712,478
14        83,706,980

In [6]:
df_final.head(60)

,Bucket,Category,0-2m_Current_2025,0-2m_Future_2030,2-3m_Current_2025,2-3m_Future_2030,3-5m_Current_2025,3-5m_Future_2030
0,GAFO,Apparel and Services,"46,968,852","53,110,985","55,237,789","64,283,981","197,380,480","224,518,227"
1,GAFO,Men's,"9,227,748","10,434,001","10,859,665","12,639,777","38,956,403","44,309,429"
2,GAFO,Women's,"15,620,036","17,663,057","19,002,977","22,098,818","68,040,660","77,391,529"
3,GAFO,Children's,"6,836,102","7,730,068","7,571,395","8,811,384","26,599,408","30,241,013"
4,GAFO,Footwear,"10,791,770","12,204,167","12,261,767","14,292,310","43,481,923","49,465,745"
5,GAFO,Watches & Jewelry,"3,632,395","4,106,686","4,521,755","5,254,969","16,563,669","18,857,199"
6,GAFO,Apparel Products and Services (1),"860,800","973,006","1,020,230","1,186,723","3,738,417","4,253,312"
7,GAFO,Computers and Hardware for Home Use,"4,381,080","4,954,698","5,197,343","6,052,767","18,525,189","21,075,426"
8,Other,Portable Memory,"74,237","84,023","90,168","105,216","313,953","357,350"
9,GAFO,Computer Software,"342,604","387,772","409,561","478,629","1,412,563","1,608,321"
10,GAFO,Computer Accessories,"371,775","420,402","441,495","514,597","1,588,104","1,808,170"
11,Other,Educational Books/Supplies/Other Expenditures,"1,868,193","2,113,744","2,198,872","2,565,193","7,758,436","8,821,751"
12,Other,Other School Supplies,"1,619,410","1,831,078","1,934,637","2,249,942","6,969,609","7,925,570"
13,GAFO,Entertainment & Recreation,"71,766,922","81,117,958","86,193,633","100,145,018","317,143,341","360,712,478"
14,GAFO,Fees and Admissions,"16,225,994","18,334,968","19,588,483","22,722,561","73,576,337","83,706,980"
15,Other,Membership Fees for Clubs (2),"5,426,940","6,132,727","6,697,423","7,768,382","25,180,646","28,646,525"
16,GAFO,"Fees for Participant Sports, excl. Trips","2,865,919","3,238,449","3,471,779","4,022,092","12,973,452","14,751,593"
17,Other,Tickets to Theatre/Operas/Concerts,"1,993,271","2,252,489","2,405,007","2,795,683","9,033,021","10,284,099"
18,Other,Tickets to Movies,"741,359","838,526","851,784","994,018","3,034,334","3,453,364"
19,Other,Tickets to Parks or Museums,"742,915","839,396","854,895","992,965","3,184,981","3,625,803"
20,Other,"Admission to Sporting Events, excl. Trips","1,616,278","1,827,030","1,955,861","2,268,234","7,189,623","8,168,639"
21,Other,Fees for Recreational Lessons,"2,812,253","3,175,742","3,318,640","3,842,401","12,866,504","14,647,111"
22,Other,Dating Services,"27,060","30,610","33,094","38,785","113,777","129,846"
23,GAFO,TV/Video/Audio,"22,634,169","25,590,101","26,767,032","31,137,438","96,282,882","109,467,331"
24,Other,Cable and Satellite Television Services,"11,203,158","12,658,651","13,597,459","15,773,029","49,971,954","56,800,909"
25,Other,Televisions,"2,346,216","2,653,537","2,728,944","3,177,859","9,639,970","10,961,342"
26,Other,Satellite Dishes,"22,388","25,308","26,669","31,139","96,241","109,590"
27,GAFO,"VCRs, Video Cameras, and DVD Players","75,987","85,934","90,015","104,706","319,785","363,413"
28,GAFO,Miscellaneous Video Equipment,"920,109","1,041,188","864,951","1,015,939","2,821,331","3,199,887"
29,GAFO,Video Cassettes and DVDs,"82,128","92,835","101,059","117,983","369,096","420,894"
30,GAFO,Video Game Hardware/Accessories,"1,010,688","1,144,341","1,166,447","1,365,049","3,971,064","4,516,613"
31,GAFO,Video Game Software,"503,729","570,457","601,031","705,355","2,052,063","2,337,431"
32,GAFO,Rental/Streaming/Downloaded Video,"3,864,302","4,372,376","4,496,575","5,247,033","15,740,940","17,902,077"
33,Other,Installation of Televisions,"24,204","27,323","30,669","35,412","119,002","135,496"
34,GAFO,Audio (3),"2,537,110","2,868,162","3,010,055","3,501,857","11,002,007","12,515,818"
35,GAFO,Rental of TV/VCR/Radio/Sound Equipment,"4,688","5,323","7,052","8,222","23,177","26,300"
36,GAFO,Repair of TV/Radio/Sound Equipment,"39,461","44,667","46,107","53,856","156,249","177,561"
37,GAFO,Pets,"17,972,027","20,313,213","21,791,116","25,318,396","80,306,420","91,334,598"
38,GAFO,Toys/Games/Crafts/Hobbies (4),"3,259,383","3,685,770","3,905,898","4,545,679","14,081,561","16,017,325"
39,Other,Recreational Vehicles and Fees (5),"3,036,809","3,429,604","3,689,025","4,263,865","14,109,151","16,036,034"
40,GAFO,Sports/Recreation/Exercise Equipment (6),"4,444,127","5,024,508","5,327,722","6,198,102","19,530,934","22,217,829"
41,Other,Photo Equipment and Supplies (7),"1,201,593","1,358,165","1,497,400","1,740,825","5,562,884","6,334,637"
42,Other,Reading (8),"2,172,100","2,454,553","2,664,016","3,098,172","10,007,336","11,396,410"
43,GAFO,Live Entertainment-for Catered Affairs,"340,392","384,310","409,844","475,979","1,609,302","1,834,789"
44,Other,Rental of Party Supplies for Catered Affairs,"480,328","542,766","553,096","644,000","2,076,534","2,366,545"
45,Other,Food,"217,558,595","245,991,645","255,231,740","297,027,011","915,472,605","1,041,244,305"
46,NG&S,Food at Home,"139,369,490","157,583,091","163,892,911","190,703,098","586,849,015","667,403,080"
47,NG&S,Bakery and Cereal Products,"18,225,788","20,605,722","21,696,917","25,232,726","78,246,016","88,992,430"
48,NG&S,"Meats, Poultry, Fish, and Eggs","29,477,976","33,330,797","34,019,787","39,592,033","120,835,041","137,391,694"
49,NG&S,Dairy Products,"14,018,464","15,849,864","16,488,052","19,184,784","59,209,296","67,337,026"
50,NG&S,Fruits and Vegetables,"23,746,888","26,845,615","27,937,052","32,498,347","100,837,861","114,717,610"
51,NG&S,Snacks and Other Food at Home (9),"53,900,374","60,951,093","63,751,103","74,195,208","227,720,803","258,964,320"
52,F&B,Food Away from Home,"78,189,105","88,408,554","91,338,829","106,323,914","328,623,590","373,841,225"
53,F&B,Alcoholic Beverages,"12,042,192","13,611,226","14,642,861","17,013,868","54,066,844","61,527,422"
54,Other,Value of Stocks/Bonds/Mutual Funds,"691,784,063","780,840,385","905,344,112","1,046,016,157","3,617,795,657","4,116,305,196"
55,Other,Value of Retirement Plans,"2,244,939,101","2,533,913,412","2,880,802,292","3,324,334,419","11,371,307,663","12,925,493,764"
56,Other,Value of Other Financial Assets,"209,108,605","236,121,674","262,885,247","303,502,068","999,384,729","1,135,284,656"
57,Other,Vehicle Loan Amount excluding Interest,"69,492,500","78,603,538","79,645,060","92,716,389","279,390,281","317,447,965"
58,Other,Value of Credit Card Debt,"55,634,871","62,891,081","65,870,606","76,552,562","238,201,909","270,881,991"
59,NG&S,Nonprescription Drugs,"3,580,105","4,047,777","4,289,430","4,986,814","15,476,019","17,592,122"

In [7]:
import pandas as pd
import os

# 1. SETUP - Define paths
base_dir = "../data/Retail"
demand_file = os.path.join(base_dir, "Retail_Demand_Outlook_4170_E_Ponce_de_Leon_Ave_Clarkston_Georgia_30021_2.xlsx")

# 2. LOAD DATA with error handling for file not found
print("Loading Demand Data...")
if not os.path.exists(demand_file):
    raise FileNotFoundError(f"Input Excel file does not exist: {demand_file}")

df = pd.read_excel(demand_file, header=None, engine="openpyxl")

# 3. HELPER FUNCTIONS
def clean_num(val):
    if pd.isna(val): return 0
    s = str(val).replace(',', '').strip()
    try:
        return float(s)
    except Exception:
        return 0

def get_vals(row_idx):
    """Extracts Current and Future spending for all three rings."""
    try:
        return {
            '0-2m_Current': clean_num(df.iloc[row_idx, 1]) if row_idx < len(df) else 0,
            '0-2m_Future': clean_num(df.iloc[row_idx, 2]) if row_idx < len(df) else 0,
            '2-3m_Current': clean_num(df.iloc[row_idx, 6]) if row_idx < len(df) else 0,
            '2-3m_Future': clean_num(df.iloc[row_idx, 7]) if row_idx < len(df) else 0,
            '3-5m_Current': clean_num(df.iloc[row_idx, 11]) if row_idx < len(df) else 0,
            '3-5m_Future': clean_num(df.iloc[row_idx, 12]) if row_idx < len(df) else 0,
        }
    except Exception:
        return {
            '0-2m_Current': 0,
            '0-2m_Future': 0,
            '2-3m_Current': 0,
            '2-3m_Future': 0,
            '3-5m_Current': 0,
            '3-5m_Future': 0
        }

# 4. DEFINE MAPPING (Excluding summaries to avoid double-counting)
mapping_defs = [
    ('Apparel and Services', 20, list(range(21, 27))),
    ('Computer', 27, list(range(28, 32))),
    ('Education', 32, list(range(33, 35))),
    ('Entertainment & Recreation', 38, list(range(40, 48)) + list(range(49, 62)) + list(range(62, 70))),
    ('Food', 73, [74, 80]), # Food at Home and Food Away
    ('Alcoholic Beverages', 81, [81]),
    ('Financial', 82, list(range(83, 88))),
    ('Health', 88, list(range(89, 94))),
    ('Home', 94, list(range(95, 99))),
    ('Household Furnishings and Equipment', 102, list(range(103, 111))),
    ('Household Operations', 111, list(range(112, 115))),
    ('Housekeeping Supplies (17)', 115, [115]),
    ('Insurance', 116, list(range(117, 121))),
    ('Transportation', 121, list(range(122, 125))),
    ('Travel', 125, list(range(126, 130)))
]

# 5. ROBUSTNESS CHECKS (Verifying math against ESRI parents)
print("\n" + "="*50)
print("    ROBUSTNESS CHECKS (0-2 MILE RING)")
print("="*50)

def verify_category(parent_idx, child_indices, label):
    parent_val = get_vals(parent_idx)['0-2m_Current']
    child_sum = sum(get_vals(i)['0-2m_Current'] for i in child_indices)
    # If parent_val is 0 (NaN in Excel), we check the next header row if available or just verify children
    status = "PASS" if abs(parent_val - child_sum) < 10 or parent_val == 0 else "REVIEW"
    print(f"{label.ljust(30)} | Parent: {parent_val:12,.0f} | Sum: {child_sum:12,.0f} | {status}")

# Check that indices are in range before running checks to prevent index errors
# (Typically these cell indices should match the input, but we'll warn if otherwise)
max_idx = len(df) - 1
def safe_range(start, end):
    return [i for i in range(start, end) if i <= max_idx]
def safe_indices(indices):
    return [i for i in indices if i <= max_idx]

try:
    verify_category(73, safe_indices([74, 80]), "Food Total")
    verify_category(20, safe_range(21, 27), "Apparel Total")
    verify_category(38, safe_indices([39, 48, 62, 63, 64, 65, 66, 67, 68, 69]), "Entertainment Total")
    verify_category(39, safe_range(40, 48), "Fees & Admissions")
    verify_category(48, safe_range(49, 62), "TV/Video/Audio")
    verify_category(111, safe_indices([112, 113, 114, 115]), "Household Operations Total")
except Exception as e:
    print(f"Warning: Robustness check failed due to data shape or unexpected indices. {e}")

# 6. BUILD CLEAN DATASET
final_rows = []
for cat_name, _, indices in mapping_defs:
    for idx in indices:
        # Do not index out of range
        if idx > max_idx:
            continue
        item_name = str(df.iloc[idx, 0]).strip() if idx < len(df) else ""
        # For Food at Home already handled by mapping_defs selection
        row_data = get_vals(idx)
        row_data['Category'] = cat_name
        row_data['Line Item'] = item_name
        final_rows.append(row_data)

df_final = pd.DataFrame(final_rows)
# Reorder for clarity
cols = ['Category', 'Line Item', '0-2m_Current', '0-2m_Future', '2-3m_Current', '2-3m_Future', '3-5m_Current', '3-5m_Future']
df_final = df_final[cols]

# 7. FINAL SUMMARY & EXPORT
print("\n" + "="*50)
print(f"Total Unique Line Items: {len(df_final)}")
print(f"Total 0-2m Current Spend: ${df_final['0-2m_Current'].sum():,.0f}")
print("="*50)

output_csv = os.path.join(base_dir, "Clean_Retail_Expenditures_No_Double_Counting.csv")
try:
    df_final.to_csv(output_csv, index=False)
    print(f"\nSuccess! File saved to: {output_csv}")
except Exception as e:
    print(f"ERROR: Could not write to CSV. {e}")

Loading Demand Data...

==================================================
    ROBUSTNESS CHECKS (0-2 MILE RING)
==================================================
Food Total                     | Parent:  217,558,595 | Sum:  217,558,595 | PASS
Apparel Total                  | Parent:   46,968,852 | Sum:   46,968,851 | PASS
Entertainment Total            | Parent:   71,766,922 | Sum:   71,766,922 | PASS
Fees & Admissions              | Parent:   16,225,994 | Sum:   16,225,995 | PASS
TV/Video/Audio                 | Parent:   22,634,169 | Sum:   22,634,168 | PASS
Household Operations Total     | Parent:            0 | Sum:   39,811,842 | PASS

==================================================
Total Unique Line Items: 81
Total 0-2m Current Spend: $4,505,667,779
==================================================

Success! File saved to: ../data/Retail/Clean_Retail_Expenditures_No_Double_Counting.csv

In [8]:
from IPython.display import display

# Show all rows of df_final in display
with pd.option_context('display.max_rows', None):
    display(df_final)

,Category,Line Item,0-2m_Current,0-2m_Future,2-3m_Current,2-3m_Future,3-5m_Current,3-5m_Future
0,Apparel and Services,Men's,"9,227,748","10,434,001","10,859,665","12,639,777","38,956,403","44,309,429"
1,Apparel and Services,Women's,"15,620,036","17,663,057","19,002,977","22,098,818","68,040,660","77,391,529"
2,Apparel and Services,Children's,"6,836,102","7,730,068","7,571,395","8,811,384","26,599,408","30,241,013"
3,Apparel and Services,Footwear,"10,791,770","12,204,167","12,261,767","14,292,310","43,481,923","49,465,745"
4,Apparel and Services,Watches & Jewelry,"3,632,395","4,106,686","4,521,755","5,254,969","16,563,669","18,857,199"
5,Apparel and Services,Apparel Products and Services (1),"860,800","973,006","1,020,230","1,186,723","3,738,417","4,253,312"
6,Computer,Computers and Hardware for Home Use,"4,381,080","4,954,698","5,197,343","6,052,767","18,525,189","21,075,426"
7,Computer,Portable Memory,"74,237","84,023","90,168","105,216","313,953","357,350"
8,Computer,Computer Software,"342,604","387,772","409,561","478,629","1,412,563","1,608,321"
9,Computer,Computer Accessories,"371,775","420,402","441,495","514,597","1,588,104","1,808,170"
10,Education,Educational Books/Supplies/Other Expenditures,"1,868,193","2,113,744","2,198,872","2,565,193","7,758,436","8,821,751"
11,Education,Other School Supplies,"1,619,410","1,831,078","1,934,637","2,249,942","6,969,609","7,925,570"
12,Entertainment & Recreation,Membership Fees for Clubs (2),"5,426,940","6,132,727","6,697,423","7,768,382","25,180,646","28,646,525"
13,Entertainment & Recreation,"Fees for Participant Sports, excl. Trips","2,865,919","3,238,449","3,471,779","4,022,092","12,973,452","14,751,593"
14,Entertainment & Recreation,Tickets to Theatre/Operas/Concerts,"1,993,271","2,252,489","2,405,007","2,795,683","9,033,021","10,284,099"
15,Entertainment & Recreation,Tickets to Movies,"741,359","838,526","851,784","994,018","3,034,334","3,453,364"
16,Entertainment & Recreation,Tickets to Parks or Museums,"742,915","839,396","854,895","992,965","3,184,981","3,625,803"
17,Entertainment & Recreation,"Admission to Sporting Events, excl. Trips","1,616,278","1,827,030","1,955,861","2,268,234","7,189,623","8,168,639"
18,Entertainment & Recreation,Fees for Recreational Lessons,"2,812,253","3,175,742","3,318,640","3,842,401","12,866,504","14,647,111"
19,Entertainment & Recreation,Dating Services,"27,060","30,610","33,094","38,785","113,777","129,846"
20,Entertainment & Recreation,Cable and Satellite Television Services,"11,203,158","12,658,651","13,597,459","15,773,029","49,971,954","56,800,909"
21,Entertainment & Recreation,Televisions,"2,346,216","2,653,537","2,728,944","3,177,859","9,639,970","10,961,342"
22,Entertainment & Recreation,Satellite Dishes,"22,388","25,308","26,669","31,139","96,241","109,590"
23,Entertainment & Recreation,"VCRs, Video Cameras, and DVD Players","75,987","85,934","90,015","104,706","319,785","363,413"
24,Entertainment & Recreation,Miscellaneous Video Equipment,"920,109","1,041,188","864,951","1,015,939","2,821,331","3,199,887"
25,Entertainment & Recreation,Video Cassettes and DVDs,"82,128","92,835","101,059","117,983","369,096","420,894"
26,Entertainment & Recreation,Video Game Hardware/Accessories,"1,010,688","1,144,341","1,166,447","1,365,049","3,971,064","4,516,613"
27,Entertainment & Recreation,Video Game Software,"503,729","570,457","601,031","705,355","2,052,063","2,337,431"
28,Entertainment & Recreation,Rental/Streaming/Downloaded Video,"3,864,302","4,372,376","4,496,575","5,247,033","15,740,940","17,902,077"
29,Entertainment & Recreation,Installation of Televisions,"24,204","27,323","30,669","35,412","119,002","135,496"
30,Entertainment & Recreation,Audio (3),"2,537,110","2,868,162","3,010,055","3,501,857","11,002,007","12,515,818"
31,Entertainment & Recreation,Rental of TV/VCR/Radio/Sound Equipment,"4,688","5,323","7,052","8,222","23,177","26,300"
32,Entertainment & Recreation,Repair of TV/Radio/Sound Equipment,"39,461","44,667","46,107","53,856","156,249","177,561"
33,Entertainment & Recreation,Pets,"17,972,027","20,313,213","21,791,116","25,318,396","80,306,420","91,334,598"
34,Entertainment & Recreation,Toys/Games/Crafts/Hobbies (4),"3,259,383","3,685,770","3,905,898","4,545,679","14,081,561","16,017,325"
35,Entertainment & Recreation,Recreational Vehicles and Fees (5),"3,036,809","3,429,604","3,689,025","4,263,865","14,109,151","16,036,034"
36,Entertainment & Recreation,Sports/Recreation/Exercise Equipment (6),"4,444,127","5,024,508","5,327,722","6,198,102","19,530,934","22,217,829"
37,Entertainment & Recreation,Photo Equipment and Supplies (7),"1,201,593","1,358,165","1,497,400","1,740,825","5,562,884","6,334,637"
38,Entertainment & Recreation,Reading (8),"2,172,100","2,454,553","2,664,016","3,098,172","10,007,336","11,396,410"
39,Entertainment & Recreation,Live Entertainment-for Catered Affairs,"340,392","384,310","409,844","475,979","1,609,302","1,834,789"
40,Entertainment & Recreation,Rental of Party Supplies for Catered Affairs,"480,328","542,766","553,096","644,000","2,076,534","2,366,545"
41,Food,Food at Home,"139,369,490","157,583,091","163,892,911","190,703,098","586,849,015","667,403,080"
42,Food,Food Away from Home,"78,189,105","88,408,554","91,338,829","106,323,914","328,623,590","373,841,225"
43,Alcoholic Beverages,Alcoholic Beverages,"12,042,192","13,611,226","14,642,861","17,013,868","54,066,844","61,527,422"
44,Financial,Value of Stocks/Bonds/Mutual Funds,"691,784,063","780,840,385","905,344,112","1,046,016,157","3,617,795,657","4,116,305,196"
45,Financial,Value of Retirement Plans,"2,244,939,101","2,533,913,412","2,880,802,292","3,324,334,419","11,371,307,663","12,925,493,764"
46,Financial,Value of Other Financial Assets,"209,108,605","236,121,674","262,885,247","303,502,068","999,384,729","1,135,284,656"
47,Financial,Vehicle Loan Amount excluding Interest,"69,492,500","78,603,538","79,645,060","92,716,389","279,390,281","317,447,965"
48,Financial,Value of Credit Card Debt,"55,634,871","62,891,081","65,870,606","76,552,562","238,201,909","270,881,991"
49,Health,Nonprescription Drugs,"3,580,105","4,047,777","4,289,430","4,986,814","15,476,019","17,592,122"
50,Health,Prescription Drugs,"6,830,756","7,720,203","8,668,938","10,049,537","31,852,880","36,167,521"
51,Health,Eyeglasses and Contact Lenses,"2,216,958","2,505,158","2,681,108","3,112,325","9,997,196","11,368,993"
52,Health,Personal Care Products (10),"11,724,578","13,263,217","13,679,762","15,947,467","48,093,942","54,688,588"
53,Health,Smoking Products,"8,941,794","10,121,497","10,775,975","12,575,507","36,637,313","41,623,716"
54,Home,Mortgage Payment and Basics (11),"204,696,467","230,995,009","247,804,008","285,937,377","968,202,711","1,100,750,472"
55,Home,Maintenance and Remodeling Services,"68,465,449","77,261,203","84,211,461","97,151,118","331,092,097","376,335,536"
56,Home,Maintenance and Remodeling Materials (12),"11,633,973","13,129,150","13,800,671","15,918,288","53,901,698","61,214,429"
57,Home,"Utilities, Fuel, and Public Services","110,026,824","124,399,068","128,722,381","149,683,736","459,755,018","522,511,840"
58,Household Furnishings and Equipment,Household Textiles (13),"2,275,763","2,573,337","2,641,888","3,075,789","9,429,651","10,723,745"
59,Household Furnishings and Equipment,Furniture,"16,344,346","18,479,749","19,460,473","22,618,681","70,126,996","79,727,487"
60,Household Furnishings and Equipment,Rugs,"671,018","758,228","827,269","959,686","3,087,263","3,512,855"
61,Household Furnishings and Equipment,Major Appliances (14),"8,763,735","9,900,982","10,283,282","11,922,870","38,026,030","43,219,241"
62,Household Furnishings and Equipment,Housewares (15),"1,784,655","2,017,727","2,126,073","2,475,595","7,687,728","8,747,196"
63,Household Furnishings and Equipment,Small Appliances,"24,155,446","27,305,236","28,950,191","33,646,838","106,032,198","120,614,533"
64,Household Furnishings and Equipment,Luggage,"447,753","506,166","542,224","630,208","1,984,937","2,258,608"
65,Household Furnishings and Equipment,Telephones and Accessories,"1,370,089","1,548,107","1,741,688","2,018,899","6,530,005","7,427,067"
66,Household Operations,Child Care,"10,745,464","12,144,737","12,674,293","14,702,585","46,989,276","53,475,690"
67,Household Operations,Lawn/Garden (16),"10,429,440","11,777,408","12,942,862","14,961,087","49,474,234","56,214,834"
68,Household Operations,Moving/Storage/Freight Express,"2,613,160","2,956,406","3,031,026","3,542,154","10,674,656","12,159,206"
69,Housekeeping Supplies (17),Housekeeping Supplies (17),"16,023,778","18,118,154","18,896,574","21,983,362","67,708,258","76,978,477"
70,Insurance,Owners and Renters Insurance,"13,661,354","15,428,754","16,415,181","18,982,977","61,551,948","69,902,618"
71,Insurance,Vehicle Insurance,"43,364,260","49,049,552","49,636,451","57,826,294","173,294,488","196,947,656"
72,Insurance,Life/Other Insurance,"11,339,368","12,810,430","13,767,053","15,944,952","51,816,242","58,897,171"
73,Insurance,Health Insurance,"85,869,725","97,049,683","103,220,082","119,812,626","377,579,722","429,142,483"
74,Transportation,Payments on Vehicles excluding Leases,"57,587,554","65,127,174","66,427,858","77,285,699","234,678,827","266,656,494"
75,Transportation,"Gasoline, Diesel Fuel, & Electric Vehicle Char...","67,617,268","76,468,176","77,272,934","89,959,659","271,519,112","308,579,635"
76,Transportation,Vehicle Maintenance and Repairs,"25,293,853","28,603,590","29,541,568","34,393,946","105,394,293","119,831,926"
77,Travel,Airline Fares,"14,633,575","16,532,045","17,590,975","20,417,638","66,511,784","75,721,970"
78,Travel,Lodging on Trips,"17,939,591","20,263,947","22,095,712","25,590,901","84,296,764","95,888,460"
79,Travel,Auto/Truck Rental on Trips,"2,184,306","2,469,227","2,622,108","3,047,961","9,636,390","10,964,442"
80,Travel,Food and Drink on Trips,"14,482,375","16,365,109","17,521,837","20,329,595","65,316,965","74,304,375"

# Supply Side

In [9]:
# Read in the following dataframes
class_a_retail_df = pd.read_excel("../data/Retail/Class_A_Retail.xlsx")
all_retail_df = pd.read_excel("../data/Retail/All_Retail.xlsx")
comps_retail_df = pd.read_excel("../data/Retail/Comps_Retail.xlsx")

In [10]:
class_a_retail_df.head()

,Period,Inventory Bldgs,Inventory SF,Vacant SF Direct,Vacant SF Sublet,Vacant SF Total,Vacant Percent % Direct,Vacant Percent % Sublet,Vacant Percent % Total,Total Available SF Direct,...,Deliveries Bldgs,Deliveries SF,Under Construction Bldgs,Under Construction SF,All Service Type Rent Direct,All Service Type Rent Sublet,All Service Type Rent Overall,NNN Rent Direct,NNN Rent Sublet,NNN Rent Overall
0,2026 YTD,4,162309,700,-,700,0,-,0,700,...,-,-,-,-,-,-,-,-,-,-
1,2025,4,162309,700,-,700,0,-,0,700,...,-,-,-,-,-,-,-,-,-,-
2,2024,4,162309,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
3,2023,4,162309,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
4,2022,4,162309,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-

In [11]:
#print columns of class_a_retail_df
print(class_a_retail_df.columns)
#print columns of all_retail_df
print(all_retail_df.columns)

Index(['  Period', 'Inventory Bldgs', 'Inventory SF', 'Vacant SF Direct',
       'Vacant SF Sublet', 'Vacant SF Total', 'Vacant Percent % Direct',
       'Vacant Percent % Sublet', 'Vacant Percent % Total',
       'Total Available SF Direct', 'Total Available SF Sublet',
       'Total Available SF Total', 'Total Available Percent % Direct',
       'Total Available Percent % Sublet', 'Total Available Percent % Total',
       'Vacant Available SF Direct', 'Vacant Available SF Sublet',
       'Vacant Available SF Total', 'Vacant Available Percent % Direct',
       'Vacant Available Percent % Sublet', 'Vacant Available Percent % Total',
       'Occupancy SF', 'Occupancy Percent', 'Net Absorption SF Direct',
       'Net Absorption SF Sublet', 'Net Absorption SF Total',
       'Gross Absorption SF Direct', 'Gross Absorption SF Sublet',
       'Gross Absorption SF Total', 'Leasing Activity Deals Direct',
       'Leasing Activity Deals Sublet', 'Leasing Activity Deals Total',
       'Leasing Activity SF Direct', 'Leasing Activity SF Sublet',
       'Leasing Activity SF Total', 'Deliveries Bldgs', 'Deliveries SF',
       'Under Construction Bldgs', 'Under Construction SF',
       'All Service Type Rent Direct', 'All Service Type Rent Sublet',
       'All Service Type Rent Overall', 'NNN Rent Direct', 'NNN Rent Sublet',
       'NNN Rent Overall'],
      dtype='object')
Index(['  Period', 'Inventory Bldgs', 'Inventory SF', 'Vacant SF Direct',
       'Vacant SF Sublet', 'Vacant SF Total', 'Vacant Percent % Direct',
       'Vacant Percent % Sublet', 'Vacant Percent % Total',
       'Total Available SF Direct', 'Total Available SF Sublet',
       'Total Available SF Total', 'Total Available Percent % Direct',
       'Total Available Percent % Sublet', 'Total Available Percent % Total',
       'Vacant Available SF Direct', 'Vacant Available SF Sublet',
       'Vacant Available SF Total', 'Vacant Available Percent % Direct',
       'Vacant Available Percent % Sublet', 'Vacant Available Percent % Total',
       'Occupancy SF', 'Occupancy Percent', 'Net Absorption SF Direct',
       'Net Absorption SF Sublet', 'Net Absorption SF Total',
       'Gross Absorption SF Direct', 'Gross Absorption SF Sublet',
       'Gross Absorption SF Total', 'Leasing Activity Deals Direct',
       'Leasing Activity Deals Sublet', 'Leasing Activity Deals Total',
       'Leasing Activity SF Direct', 'Leasing Activity SF Sublet',
       'Leasing Activity SF Total', 'Deliveries Bldgs', 'Deliveries SF',
       'Under Construction Bldgs', 'Under Construction SF',
       'All Service Type Rent Direct', 'All Service Type Rent Sublet',
       'All Service Type Rent Overall', 'NNN Rent Direct', 'NNN Rent Sublet',
       'NNN Rent Overall'],
      dtype='object')

In [12]:
import re

def clean_period(period_val):
    # Extract year from values like "2026 YTD" or "2024"
    match = re.search(r'(\d{4})', str(period_val))
    return int(match.group(1)) if match else None

def clean_numeric(val):
    # Remove commas and dash or spaces, handle empty or "-" as NaN
    val = str(val).replace(',', '').strip()
    if val == '-' or val == '':
        return float('nan')
    try:
        return float(val)
    except Exception:
        return float('nan')

def compute_avg_vacancy(df, name="df"):
    # Find the correct column names, accounting for spaces
    period_col = [col for col in df.columns if col.strip().lower() == "period"][0]
    vacancy_col = None
    avail_col = None
    for candidate in ['Vacant Percent % Total', 'Vacant Percent% Total', 'Vacant Percent %Total']:
        matches = [col for col in df.columns if candidate.replace(' ', '').lower() == col.replace(' ', '').lower()]
        if matches:
            vacancy_col = matches[0]
            break
    # Update: look for 'Total Available SF Total' as the available SF column
    for candidate in ['Total Available SF Total']:
        matches = [col for col in df.columns if candidate.replace(' ', '').lower() == col.replace(' ', '').lower()]
        if matches:
            avail_col = matches[0]
            break
    if vacancy_col is None:
        raise ValueError(f"Could not find vacancy column in {name}")
    if avail_col is None:
        # If not found, skip printing Total Available SF and print a message
        print(f"WARNING: Could not find Total Available SF Total column in {name}")
    # Clean columns
    df = df.copy()
    df['Year'] = df[period_col].apply(clean_period)
    df['Vacant_Percent_Total'] = df[vacancy_col].apply(clean_numeric)
    # Multiply by 100 and round to two decimals to be clear
    df['Vacant_Percent_Total'] = (df['Vacant_Percent_Total'] * 100).round(2)
    # If available, clean Total Available SF Total column
    if avail_col:
        df['Total_Available_SF_Clean'] = df[avail_col].apply(clean_numeric)
    # Filter last three years (2023–2026)
    df_recent = df[df['Year'].isin([2024, 2025, 2026, 2023])]
    recent_years = sorted(df_recent['Year'].dropna().unique())[-3:]
    df_recent = df[df['Year'].isin(recent_years)]
    avg_recent = df_recent['Vacant_Percent_Total'].mean()
    avg_total = df['Vacant_Percent_Total'].mean()
    # Get 2026 vacancy if present
    vacancy_2026 = None
    if 2026 in df['Year'].values:
        row_2026 = df[df['Year'] == 2026]
        if not row_2026.empty:
            vacancy_2026 = row_2026['Vacant_Percent_Total'].mean()
    print(f"{name}:")
    print(f"  Vacancy Rate (last 3 years {recent_years}): {avg_recent:.2f}%")
    print(f"  Vacancy Rate (all years): {avg_total:.2f}%")
    if vacancy_2026 is not None and not pd.isna(vacancy_2026):
        print(f"  Vacancy Rate (2026): {vacancy_2026:.2f}%")
    else:
        print(f"  Vacancy Rate (2026): N/A")
    # Print Total Available SF Total if column exists and value is not NaN for 2026
    if avail_col:
        if 2026 in df['Year'].values:
            row_2026 = df[df['Year'] == 2026]
            total_available_2026 = row_2026['Total_Available_SF_Clean'].sum()
            if not pd.isna(total_available_2026):
                print(f"  Total Available SF Total (2026): {int(total_available_2026):,}")
            else:
                print(f"  Total Available SF Total (2026): N/A")
        total_available_sum = df['Total_Available_SF_Clean'].sum()
        print(f"  Total Available SF Total (all years sum): {int(total_available_sum):,}")
    print("")

compute_avg_vacancy(class_a_retail_df, name="Class A Retail")
compute_avg_vacancy(all_retail_df, name="All Retail")

Class A Retail:
  Vacancy Rate (last 3 years [2024, 2025, 2026]): 0.40%
  Vacancy Rate (all years): 4.53%
  Vacancy Rate (2026): 0.40%
  Total Available SF Total (2026): 700
  Total Available SF Total (all years sum): 107,646

All Retail:
  Vacancy Rate (last 3 years [2024, 2025, 2026]): 6.93%
  Vacancy Rate (all years): 7.45%
  Vacancy Rate (2026): 6.30%
  Total Available SF Total (2026): 186,557
  Total Available SF Total (all years sum): 4,887,189

In [13]:
import pandas as pd
pd.set_option('display.max_columns', None)
comps_retail_df.head(20)

,Address,Building Name / Owner,Year Built,Total RBA (SF),Land Area (AC),% Leased,Rent/SF,Primary Use,Anchor Tenants,Average Weighted Rent,Avg Rent-Direct (Retail),Avg Rent-Sublet (Retail),Building Operating Expenses,Building Park,Building Status,Building Tax Expenses,City,Collateral Type,Condo,Construction Begin,Continent,Country,County Name,Coworking Available Space,Cross Street,Developer Name,Direct Available Space,Direct Services,Direct Vacant Space,Features,Fema Flood Zone,FEMA Map Date,FEMA Map Identifier,FIRM ID,FIRM Panel Number,Flood Risk Area,Floodplain Area,For Sale Price Per SF,Fund Name,Has Lab Space,In SFHA,Interest Rate,Interest Rate Type,Land Area (AC).1,Land Area (SF),Leasing Company Address,Leasing Company City State Zip,Leasing Company Contact,Leasing Company Fax,Leasing Company Name,Leasing Company Phone,Loan Type,Maturity Date,Max Floor Contiguous Space,Month Renovated,Number Of Parking Spaces,Number Of Stories,Origination Amount,Origination Date,Originator,Owner Name,Parking Ratio,Percent Leased,Property Address,Property Manager Name,Property Name,Property Type,PropertyID,RBA,Sales Company,Sales Contact,Sales Contact Phone,Smallest Available Space,State,Subcontinent,Sublet Available Space,Sublet Services,Submarket Cluster,Submarket Name,Total Available Space (SF),Year Built.1,Year Renovated,Zip
0,215 Clairemont Ave,Genco Real Estate LLC,1984,5000,0,1,38,Storefront Retail/Office,NaN,38,NaN,NaN,2025 Tax @ $1.8645/sf,NaN,Existing,2025 Tax @ $1.8645/sf,Decatur,Single,No,NaN,Americas,United States,DeKalb,0,NaN,NaN,"1,742",Triple Net,1742,"Air Conditioning, Pylon Sign, Signage, Storage...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,No,NaN,Variable,0,20909,NaN,NaN,Eric Carlton,NaN,Oakhurst Realty Partners,"4,043,714,100",NaN,NaN,"1,742",NaN,30,1,"2,273,800",12/02/2021,ReadyCap Lending LLC,Genco Real Estate LLC,6,65,215 Clairemont Ave,NaN,NaN,Retail (Strip Center),6087336,5000,NaN,NaN,NaN,"1,742",GA,North America,0,NaN,Dekalb,Decatur/East Atl,"1,742",1984,NaN,30030
1,619-647 E College Ave,"Meghan Byrne, LLC",1945/04,24000,3,1,26,Freestanding,NaN,24,26,NaN,2025 Tax @ $0.3127/sf,East Decatur Station,Existing,2025 Tax @ $0.3127/sf,Decatur,NaN,No,NaN,Americas,United States,DeKalb,0,NaN,NaN,"4,950",Triple Net,4950,"Property Manager on Site, Pylon Sign, Restaura...","Area of moderate flood hazard, usually the are...",08/15/2019,13089C0068K,13089C,0068K,Moderate to Low Risk Areas,100-year and 500-year Floodplain,NaN,NaN,False,No,NaN,NaN,3,110642,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"2,200",NaN,65,2,NaN,NaN,NaN,"Meghan Byrne, LLC",3,79,619-647 E College Ave,NaN,NaN,Retail,923164,24000,NaN,NaN,NaN,"1,000",GA,North America,0,NaN,Dekalb,Decatur/East Atl,"4,950",1945,"2,004",30030
2,119-123 E Court Sq,East Court Square II LLC,1927,14448,0,1,36,Storefront Retail/Office,NaN,36,NaN,NaN,2025 Tax @ $0.7272/sf,NaN,Existing,2025 Tax @ $0.7272/sf,Decatur,NaN,No,Jul 1926,Americas,United States,DeKalb,0,NaN,NaN,"1,629",Full Service,2509,"24 Hour Access, Air Conditioning, Tenant Contr...","Area of moderate flood hazard, usually the are...",08/15/2019,13089C0068K,13089C,0068K,Moderate to Low Risk Areas,100-year and 500-year Floodplain,NaN,NaN,False,No,NaN,NaN,0,7224,NaN,NaN,Susan Poole,NaN,"Corporate Property Advisors, Inc.","4,042,755,741",NaN,NaN,"1,629",NaN,36,2,NaN,NaN,NaN,East Court Square II LLC,2,89,119-123 E Court Sq,"Corporate Property Advisors, Inc.",NaN,Retail,437449,14448,NaN,NaN,NaN,408,GA,North America,0,NaN,Dekalb,Decatur/East Atl,"1,629",1927,NaN,30030-2521
3,929 Main St,—,1929,4052,0,1,20,Restaurant,NaN,20,20,NaN,2025 Tax @ $0.3654/sf,NaN,Existing,2025 Tax @ $0.3654/sf,Stone Mountain,NaN,No,NaN,Americas,United States,DeKalb,0,NaN,NaN,"1,730",Modified Gross,1730,"Corner Lot, Restaurant",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,No,NaN,NaN,0,3049,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,730",NaN,NaN,2,NaN,NaN,NaN,Cloud Street Development Inc,0,57,929 Main St,NaN,NaN,Retail,13829974,4052,NaN,NaN,NaN,"1,730",GA,North America,0,NaN,Dekalb,Stone Mtn/Clarkston,"1,730",1929,NaN,30083
4,545 N McDonough St,The Trust Building,1922/18,12754,0,1,30,Storefront Retail/Office,NaN,30,30,NaN,2025 Tax @ $1.1032/sf,NaN,Existing,2025 Tax @ $1.1032/sf,Decatur,Single,No,NaN,Americas,United States,DeKalb,0,NaN,NaN,775,Full Service,775,Air Conditioning,"Area of moderate flood hazard, usually the are...",08/15/2019,13089C0068K,13089C,0068K,Moderate to Low Risk Areas,100-year and 500-year Floodplain,NaN,NaN,False,No,NaN,NaN,0,6534,NaN,NaN,Todd Semrau,NaN,Oakhurst Realty Partners,"4,043,714,100",NaN,11/02/2035,775,6,NaN,2,"1,385,000",11/03/2010,Metro City Bank,Apple Towns Llc,0,94,545 N McDonough St,NaN,The Trust Building,Retail,439819,12754,NaN,NaN,NaN,775,GA,North America,0,NaN,Dekalb,Decatur/East Atl,775,1922,"2,018",30030-3310
5,2960 Flowers Rd. S,Mercer University,2021,13302,10,1,27,Restaurant,NaN,NaN,NaN,NaN,NaN,NaN,Existing,NaN,Atlanta,NaN,No,NaN,Americas,United States,DeKalb,0,NaN,NaN,"5,867",NaN,5867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,No,NaN,NaN,10,436907,NaN,NaN,Bob Stasiowski,NaN,Atlantic Retail,"4,707,661,762",NaN,NaN,"2,593",NaN,54,1,NaN,NaN,NaN,Mercer University,4,56,2960 Flowers Rd. S,NaN,NaN,Retail,12293024,13302,NaN,NaN,NaN,"1,582",GA,North America,0,NaN,Dekalb,Northlake/I-85,"5,867",2021,NaN,30341
6,3088 Briarcliff Rd,Stein Investment Group,1964,5446,5,1,—,Freestanding,NaN,NaN,NaN,NaN,2025 Tax @ $1.2135/sf,Williamsburg Village Shopping Center,Existing,2025 Tax @ $1.2135/sf,Atlanta,NaN,No,NaN,Americas,United States,DeKalb,NaN,NaN,NaN,NaN,NaN,0,NaN,"Area of moderate flood hazard, usually the are...",08/15/2019,13089C0058K,13089C,0058K,Moderate to Low Risk Areas,100-year and 500-year Floodplain,NaN,NaN,False,No,NaN,NaN,5,217800,NaN,NaN,NaN,NaN,Stein Investment Group,NaN,NaN,NaN,NaN,NaN,40,2,NaN,NaN,NaN,Stein Investment Group,7,100,3088 Briarcliff Rd,NaN,NaN,Retail (Neighborhood Center),6574014,5446,NaN,NaN,NaN,NaN,GA,North America,NaN,NaN,Dekalb,Northlake/I-85,NaN,1964,NaN,30329
7,100 N Avondale Rd,Alan J Gay,1905/11,4037,0,1,—,Storefront Retail/Res.,NaN,NaN,NaN,NaN,2025 Tax @ $3.4606/sf,NaN,Existing,2025 Tax @ $3.4606/sf,Avondale Estates,NaN,No,NaN,Americas,United States,DeKalb,NaN,NaN,NaN,NaN,NaN,0,NaN,"Area of moderate flood hazard, usually the are...",05/16/2013,13089C0069J,13089C,0069J,Moderate to Low Risk Areas,100-year and 500-year Floodplain,NaN,NaN,False,No,NaN,NaN,0,14375,NaN,NaN,NaN,NaN,KW Commercial Atlanta Midtown,NaN,NaN,NaN,NaN,NaN,15,2,NaN,NaN,NaN,Alan J Gay,4,100,100 N Avondale Rd,NaN,NaN,Retail,6118507,4037,NaN,NaN,NaN,NaN,GA,North America,NaN,NaN,Dekalb,Decatur/East Atl,NaN,1905,"2,011",30002
8,2686 E College Ave,The Station,2026,5509,0,1,—,Storefront Retail/Res.,NaN,NaN,NaN,NaN,NaN,NaN,Deferred,NaN,Decatur,NaN,No,Jan 2026,Americas,United States,DeKalb,NaN,NaN,NaN,NaN,NaN,0,"24 Hour Access, Air Conditioning, Signage, Sig...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,No,NaN,NaN,0,7841,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,100,2686 E College Avenue,NaN,The Station,Retail,19261347,5509,NaN,NaN,NaN,NaN,GA,North America,NaN,NaN,Dekalb,Decatur/East Atl,NaN,2026,NaN,30030
9,970 Main St,970 Main Street Ventures,1935/17,2800,0,1,—,Storefront Retail/Res.,NaN,NaN,NaN,NaN,2025 Tax @ $1.4247/sf,NaN,Existing,2025 Tax @ $1.4247/sf,Stone Mountain,NaN,No,NaN,Americas,United States,DeKalb,NaN,NaN,NaN,NaN,NaN,0,"Air Conditioning, Balcony, Corner Lot, PATH, R...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,No,NaN,NaN,0,1777,NaN,NaN,NaN,NaN,PalmerHouse Properties,NaN,NaN,NaN,NaN,NaN,3,2,NaN,NaN,NaN,970 Main Street Ventures LLC,1,100,970 Main St,NaN,NaN,Retail,10545247,2800,NaN,NaN,NaN,NaN,GA,North America,NaN,NaN,Dekalb,Stone Mtn/Clarkston,NaN,1935,"2,017",30083-3063
10,106-128 N Avondale Rd,Retail Space / J. Guest,1912,13852,0,1,32,Storefront Retail/Office,NaN,32,32,NaN,2025 Tax @ $1.4335/sf,NaN,Existing,2025 Tax @ $1.4335/sf,Avondale Estates,Multiple,No,NaN,Americas,United States,DeKalb,0,NaN,NaN,"1,539",Triple Net,1539,"Air Conditioning, Signage, Tenant Controlled HVAC","Area of moderate flood hazard, usually the are...",05/16/2013,13089C0069J,13089C,0069J,Moderate to Low Risk Areas,100-year and 500-year Floodplain,NaN,NaN,False,No,NaN,NaN,0,13939,NaN,NaN,Fisher Paty,NaN,Oakhurst Realty Partners,"4,043,714,100",Conventional,12/01/2032,"1,539",NaN,NaN,2,"2,325,000",12/14/2022,Peach State Federal Credit Union,Jeremy G Guest,NaN,89,106-128 N Avondale Rd,NaN,Retail Space,Retail,11405493,13852,NaN,NaN,NaN,"1,539",GA,North America,0,NaN,Dekalb,Decatur/East Atl,"1,539",1912,NaN,30002-1325
11,17 N Avondale Plz,Rubin & Sara Pichulik,1924,6000,0,1,—,Storefront Retail/Office,NaN,NaN,NaN,NaN,2025 Tax @ $1.5526/sf,NaN,Existing,2025 Tax @ $1.5526/sf,Avondale Estates,NaN,No,NaN,Americas,United States,DeKalb,NaN,NaN,NaN,NaN,NaN,0,NaN,"Area of moderate flood hazard, usually the are...",05/16/2013,13089C0069J,13089C,0069J,Moderate to Low Risk Areas,100-year and 500-year Floodplain,NaN,NaN,False,No,NaN,NaN,0,5663,NaN,NaN,NaN,NaN,Suzanne Eisenberg,NaN,NaN,NaN,NaN,NaN,12,2,NaN,NaN,NaN,Rubin & Sara Pichulik,2,100,17 N Avondale Plz,NaN,NaN,Retail,6118519,6000,NaN,NaN,NaN,NaN,GA,North America,NaN,NaN,Dekalb,Decatur/East Atl,NaN,1924,NaN,30002
12,70 N Avondale Rd,The Dale / Avondale Estates,2025,25000,2,1,—,Storefront Retail/Office,NaN,NaN,NaN,NaN,NaN,NaN,Existing,NaN,Avondale Estates,NaN,No,May 2024,Americas,United States,DeKalb,NaN,NaN,"Fabric Developers, LLC",NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,No,NaN,NaN,2,74488,NaN,NaN,Coleman Weatherholtz,NaN,Healey Weatherholtz Properties,"4,042,197,093",NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,City of Avondale Estates,NaN,100,70 N Avondale Rd,NaN,The Dale,Retail,19827138,25000,NaN,NaN,NaN,NaN,GA,North America,NaN,NaN,Dekalb,Decatur/East Atl,NaN,2025,NaN,30002
13,125 E Court Sq,Brick Store Pub,1929,3900,0,1,—,Bar/Nightclub,NaN,NaN,NaN,NaN,2025 Tax @ $0.8925/sf,NaN,Existing,2025 Tax @ $0.8925/sf,Decatur,Multiple,No,NaN,Americas,United States,DeKalb,NaN,NaN,NaN,NaN,NaN,0,"Air Conditioning, Wheelchair Accessible","Area of moderate flood hazard, usually the are...",08/15/2019,13089C0068K,13089C,0068K,Moderate to Low Risk Areas,100-year and 500-year Floodplain,NaN,NaN,False,No,NaN,NaN,0,4356,NaN,NaN,NaN,NaN,NaN,NaN,Conventional,01/01/2048,NaN,NaN,NaN,1,"1,152,000",01/27/2023,Georgia Certified Development,Brick Store Pub,NaN,100,125 E Court Sq,NaN,NaN,Retail,9365971,3900,NaN,NaN,NaN,NaN,GA,North America,NaN,NaN,Dekalb,Decatur/East Atl,NaN,1929,NaN,30030
14,975 Main St,H & B Associates,1900/85,4684,0,1,—,Storefront Retail/Office,NaN,NaN,NaN,NaN,2025 Tax @ $2.6816/sf,NaN,Existing,2025 Tax @ $2.6816/sf,Stone Mountain,NaN,No,NaN,Americas,United States,DeKalb,NaN,NaN,NaN,NaN,NaN,0,NaN,"Area of moderate flood hazard, usually the are...",12/08/2016,13089C0091K,13089C,0091K,Moderate to Low Risk Areas,100-year and 500-year Floodplain,NaN,NaN,False,No,NaN,NaN,0,3920,NaN,NaN,NaN,NaN,Knapp Commercial Advisors,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,H & B Associates,NaN,100,975 Main St,NaN,NaN,Retail,6746945,4684,NaN,NaN,NaN,NaN,GA,North America,NaN,NaN,Dekalb,Stone Mtn/Clarkston,NaN,1900,"1,985",30083-3060
15,2321 Main St,Main Street Trust,1971,2472,0,1,—,Storefront Retail/Office,NaN,NaN,NaN,NaN,2025 Tax @ $7.1602/sf,NaN,Existing,2025 Tax @ $7.1602/sf,Tucker,NaN,No,NaN,Americas,United States,DeKalb,NaN,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,No,NaN,NaN,0,2614,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,NaN,NaN,NaN,Main Street Trust,1,100,2321 Main St,NaN,NaN,Retail,439082,2472,NaN,NaN,NaN,NaN,GA,North America,NaN,NaN,Dekalb,Stone Mtn/Clarkston,NaN,1971,NaN,30084-4471
16,535 N McDonough St,DeWoskin Law Firm LLC,1960,2000,0,1,—,Storefront Retail/Office,NaN,NaN,NaN,NaN,2025 Tax @ $1.4020/sf,NaN,Existing,2025 Tax @ $1.4020/sf,Decatur,NaN,No,NaN,Americas,United States,DeKalb,NaN,NaN,NaN,NaN,NaN,0,NaN,"Area of moderate flood hazard, usually the are...",08/15/2019,13089C0068K,13089C,0068K,Moderate to Low Risk Areas,100-year and 500-year Floodplain,NaN,NaN,False,No,NaN,NaN,0,3484,NaN,NaN,NaN,NaN,Avison Young,NaN,NaN,NaN,NaN,NaN,50,1,NaN,NaN,NaN,DeWoskin Law Firm LLC,NaN,100,535 N McDonough St,"Nardone & Crecelius, L.L.C.",535 North McDonough Street,Retail,437618,2000,NaN,NaN,NaN,NaN,GA,North America,NaN,NaN,Dekalb,Decatur/East Atl,NaN,1960,NaN,30030-3309
17,131 E Trinity Pl,Oakhurst Realty Partners,1963,1757,0,1,—,Storefront Retail/Office,NaN,NaN,NaN,NaN,2025 Tax @ $1.0750/sf,NaN,Existing,2025 Tax @ $1.0750/sf,Decatur,NaN,No,NaN,Americas,United States,DeKalb,NaN,NaN,NaN,NaN,NaN,0,Signage,"Area of moderate flood hazard, usually the are...",08/15/2019,13089C0068K,13089C,0068K,Moderate to Low Risk Areas,100-year and 500-year Floodplain,NaN,NaN,False,No,NaN,NaN,0,1755,NaN,NaN,A. Barton Lester,NaN,Oakhurst Realty Partners,"4,043,710,188",NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,Oakhurst Realty Partners,NaN,100,131 E Trinity Pl,NaN,NaN,Retail,11394701,1757,NaN,NaN,NaN,NaN,GA,North America,NaN,NaN,Dekalb,Decatur/East Atl,NaN,1963,NaN,30030-3303

In [14]:
# Clean column names to remove leading/trailing spaces
comps_retail_df.columns = comps_retail_df.columns.str.strip()

# Find likely column names
def find_column(df, options):
    for opt in options:
        # This replaces spaces and lowercases for a "fuzzy" match
        matches = [col for col in df.columns if col.replace(" ", "").lower() == opt.replace(" ", "").lower()]
        if matches:
            return matches[0]
    raise ValueError(f"Column not found for options: {options}")

# Updated search options to match your specific table headers
rba_col = find_column(comps_retail_df, ['RBA', 'Total RBA (SF)', 'Total RBA'])
rent_per_sf_col = find_column(comps_retail_df, ['Rent/SF', 'Rent Per SF', 'Asking Rent/SF'])
avg_weighted_rent_col = find_column(comps_retail_df, ['Average Weighted Rent', 'Avg Weighted Rent'])
direct_avail_col = find_column(comps_retail_df, ['Direct Available Space', 'Direct Avail'])
total_avail_col = find_column(comps_retail_df, ['Total Available Space (SF)', 'Total Available SF', 'Total Avail'])
percent_leased_col = find_column(comps_retail_df, ['Percent Leased', '% Leased', 'Leased %'])

# Convert to numeric, handling commas and strings like "—"
cols_to_fix = [rba_col, rent_per_sf_col, avg_weighted_rent_col, direct_avail_col, total_avail_col, percent_leased_col]
for col in cols_to_fix:
    comps_retail_df[col] = pd.to_numeric(comps_retail_df[col].astype(str).str.replace(',', '').replace('—', ''), errors='coerce')

# Calculations
sum_rba = comps_retail_df[rba_col].sum()
avg_rent_sf = comps_retail_df[rent_per_sf_col].mean()
avg_weighted_rent = comps_retail_df[avg_weighted_rent_col].mean()
sum_direct_avail = comps_retail_df[direct_avail_col].sum()
sum_total_avail = comps_retail_df[total_avail_col].sum()

# Vacancy Rate Formulas
comps_retail_df['Vacancy Rate'] = (comps_retail_df[total_avail_col] / comps_retail_df[rba_col]) * 100
avg_vacancy_rate = comps_retail_df['Vacancy Rate'].mean()

comps_retail_df['Vacancy Rate 2'] = 100 - comps_retail_df[percent_leased_col]
avg_vacancy_rate_2 = comps_retail_df['Vacancy Rate 2'].mean()

# Output
print(f"Sum of RBA: {sum_rba:,.0f}")
print(f"Average of Rent/SF: ${avg_rent_sf:,.2f}")
print(f"Average of Average Weighted Rent: ${avg_weighted_rent:,.2f}")
print(f"Sum of Direct Available Space: {sum_direct_avail:,.0f}")
print(f"Sum of Total Available SF: {sum_total_avail:,.0f}")
print(f"Average Vacancy Rate (Total Avail / RBA): {avg_vacancy_rate:.2f}%")
print(f"Average Vacancy Rate 2 (100 - % Leased): {avg_vacancy_rate_2:.2f}%")

Sum of RBA: 151,013
Average of Rent/SF: $29.86
Average of Average Weighted Rent: $29.96
Sum of Direct Available Space: 18,232
Sum of Total Available SF: 18,232
Average Vacancy Rate (Total Avail / RBA): 24.39%
Average Vacancy Rate 2 (100 - % Leased): 9.48%

In [15]:
# Fill empty available space with 0 so they are included in the average
comps_retail_df[total_avail_col] = comps_retail_df[total_avail_col].fillna(0)

# Now calculate the rates
comps_retail_df['Vacancy Rate'] = (comps_retail_df[total_avail_col] / comps_retail_df[rba_col]) * 100
print(f"Simple Average Vacancy: {comps_retail_df['Vacancy Rate'].mean():.2f}%")

# Calculate the Portfolio (Weighted) Vacancy
portfolio_vacancy = (sum_total_avail / sum_rba) * 100
print(f"True Portfolio Vacancy: {portfolio_vacancy:.2f}%")

Simple Average Vacancy: 9.48%
True Portfolio Vacancy: 12.07%